export const DRIVER_START_LOADING = "DRIVER_START_LOADING";
export const DRIVER_STOP_LOADING = "DRIVER_STOP_LOADING";
export const DRIVER_ERROR = "DRIVER_ERROR";
export const CREATE_DRIVER = "CREATE_DRIVER";
export const GET_ALL_DRIVER = "GET_ALL_DRIVER";
export const GET_DRIVER = "GET_DRIVER";
export const UPDATE_DRIVER = "UPDATE_DRIVER";