export const DISPATCH_ORDER_START_LOADING = "DISPATCH_ORDER_START_LOADING";
export const DISPATCH_ORDER_STOP_LOADING = "DISPATCH_ORDER_STOP_LOADING";
export const DISPATCH_ORDER_ERROR = "DISPATCH_ORDER_ERROR";
export const CREATE_DISPATCH_ORDER = "CREATE_DISPATCH_ORDER";
export const GET_ALL_DISPATCH_ORDER = "GET_ALL_DISPATCH_ORDER";
export const GET_DISPATCH_ORDER = "GET_DISPATCH_ORDER";
export const UPDATE_DISPATCH_ORDER = "UPDATE_DISPATCH_ORDER";