export const STOCK_ADJUST_START_LOADING= "STOCK_ADJUST_START_LOADING";
export const STOCK_ADJUST_STOP_LOADING= "STOCK_ADJUST_STOP_LOADING";
export const STOCK_ADJUST_ERROR="STOCK_ADJUST_ERROR";
export const CREATE_STOCK_ADJUST="CREATE_STOCK_ADJUST";
export const GET_ALL_STOCK_ADJUST="GET_ALL_STOCK_ADJUST";
export const GET_STOCK_ADJUST="GET_STOCK_ADJUST";
export const DELETE_STOCK_ADJUST="DELETE_STOCK_ADJUST";