export const VEHICLE_TYPE_START_LOADING= "VEHICLE_TYPE_START_LOADING";
export const VEHICLE_TYPE_ERROR="VEHICLE_TYPE_ERROR";
export const CREATE_VEHICLE_TYPE="CREATE_VEHICLE_TYPE";
export const GET_ALL_VEHICLE_TYPE="GET_ALL_VEHICLE_TYPE";
export const GET_VEHICLE_TYPE="GET_VEHICLE_TYPE";
export const UPDATE_VEHICLE_TYPE="UPDATE_VEHICLE_TYPE";