export const PRODUCT_OUTWARD_START_LOADING = "PRODUCT_OUTWARD_START_LOADING";
export const PRODUCT_OUTWARD_STOP_LOADING = "PRODUCT_OUTWARD_STOP_LOADING";
export const PRODUCT_OUTWARD_ERROR = "PRODUCT_OUTWARD_ERROR";
export const CREATE_PRODUCT_OUTWARD = "CREATE_PRODUCT_OUTWARD";
export const GET_ALL_PRODUCT_OUTWARD = "GET_ALL_PRODUCT_OUTWARD";
export const GET_PRODUCT_OUTWARD = "GET_PRODUCT_OUTWARD";
export const EXPORT_OUTWARDS = "EXPORT_OUTWARDS";