export const BRAND_START_LOADING= "BRAND_START_LOADING";
export const BRAND_STOP_LOADING= "BRAND_STOP_LOADING";
export const BRAND_ERROR="BRAND_ERROR";
export const CREATE_BRAND="CREATE_BRAND";
export const GET_ALL_BRAND="GET_ALL_BRAND";
export const GET_BRAND="GET_BRAND";
export const UPDATE_BRAND="UPDATE_BRAND";