export const INVENTORY_START_LOADING = "INVENTORY_START_LOADING";
export const INVENTORY_STOP_LOADING = "INVENTORY_STOP_LOADING";
export const INVENTORY_ERROR = "INVENTORY_ERROR";
export const GET_ALL_INVENTORY = "GET_ALL_INVENTORY";