export const PRODUCT_INWARD_START_LOADING= "PRODUCT_INWARD_START_LOADING";
export const PRODUCT_INWARD_STOP_LOADING= "PRODUCT_INWARD_STOP_LOADING";
export const PRODUCT_INWARD_ERROR="PRODUCT_INWARD_ERROR";
export const CREATE_PRODUCT_INWARD="CREATE_PRODUCT_INWARD";
export const GET_ALL_PRODUCT_INWARD="GET_ALL_PRODUCT_INWARD";
export const GET_PRODUCT_INWARD="GET_PRODUCT_INWARD";
export const UPDATE_PRODUCT_INWARD="UPDATE_PRODUCT_INWARD";
export const EXPORT_INWARDS = "EXPORT_INWARDS";