export const VEHICLE_START_LOADING= "VEHICLE_START_LOADING";
export const VEHICLE_ERROR="VEHICLE_ERROR";
export const CREATE_VEHICLE="CREATE_VEHICLE";
export const GET_ALL_VEHICLE="GET_ALL_VEHICLE";
export const GET_VEHICLE="GET_VEHICLE";
export const UPDATE_VEHICLE="UPDATE_VEHICLE";